#####################################
# Mosquitto MQTT broker configuration
#####################################

# Persistir mensagens QoS>0 entre restarts
persistence true
persistence_location /mosquitto/data/

# Gravar logs em arquivo
log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information

# Escutar na porta padrão (0.0.0.0 = todas interfaces)
listener 1883 0.0.0.0

# Permitir conexões sem usuário/senha
allow_anonymous true

# --- opcional: descomente para força autenticação ---
# allow_anonymous false
# password_file /mosquitto/config/passwordfile

# --- TLS listener (secure MQTT over SSL) ---
listener 8883 0.0.0.0
cafile /mosquitto/config/ca.crt
certfile /mosquitto/config/server.crt
keyfile /mosquitto/config/server.key

# (Opcional) Exigir autenticação de cliente:
# require_certificate true
